Big CI improvement; works against tip of QCBOR 1.x and 2.x
Still a lot of work to do in this area; inconsistencies and such, but it's time to get the CI and builds working again.

This PR fixes compatibility with QCBOR version.  You also need the latest QCBORs to work with this because it relies on CMake package info.

This PR adds CI support for Windows.

This PR uses package managers to get OpenSSL and MbedTLS. This will make it much easier to adapt to varying versions of crypto libraries.

This PR reorganizes the fan out. It adds tests against QCBOR versions and ifdef fan out.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,3 +1,15 @@
+
+# 15 ifdefs
+# 3 qcbor versions
+# 3 compilers
+# 3 containers
+# 6 crypto libraries
+# 2 debug/release 
+
+# ifdefs X crypto 15 * 6 = 90 
+
+# qcbor X compilers X min crypto  = 3 * 2 * 3 = 18
+
 name: CI
 
 on: [push, pull_request]
@@ -9,122 +21,380 @@ jobs:
       matrix:
         c-compiler: [gcc, clang]
 
+        qcbor-version: [master, dev]
+
+        crypto:
+          - interface: Test
+            provider: Test
+            cmake: ""
+
+          - interface: psa
+            provider: MbedTLS
+            version: 3.5.2
+            cmake: -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake 
+
+#TODO: switch to later version of OpenSSL
+          - interface: OpenSSL
+            provider: OpenSSL
+            version: 1.1.1v
+            cmake: -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake 
+
+        ifdef: &ifdef-array
+          - ""
+
         config:
-        # OpenSSL 1.1.1 (Ubuntu 20.04)
-        - os-image: ubuntu-latest
-          container: ubuntu:20.04
-          crypto-provider: OpenSSL
+          - os-image: ubuntu-latest
+            container: ubuntu:22.04
 
-        # OpenSSL 3.0 (Ubuntu 22.04)
-        - os-image: ubuntu-latest
-          container: ubuntu:22.04
-          crypto-provider: OpenSSL
-        
-        - os-image: ubuntu-latest
-          container: ubuntu:20.04
-          crypto-provider: MbedTLS
-          crypto-provider-version: 'v2.28.0'
-          crypto-provider-extra: ''
-          crypto-provider-build-extra: ''
-        
-        - os-image: ubuntu-latest
-          container: ubuntu:20.04
-          crypto-provider: MbedTLS
-          crypto-provider-version: 'v3.1.0'
-          crypto-provider-extra: ''
-          crypto-provider-build-extra: ''
-
-        - os-image: ubuntu-latest
-          container: ubuntu:20.04
-          crypto-provider: MbedTLS
-          crypto-provider-version: 'v3.4.0'
-          crypto-provider-extra: ''
-          crypto-provider-build-extra: ''
-
-        - os-image: ubuntu-latest
-          container: ubuntu:20.04
-          crypto-provider: MbedTLS
-          crypto-provider-version: 'v3.4.0'
-          crypto-provider-extra: ''
-          crypto-provider-build-extra: 'python3 scripts/config.py set MBEDTLS_ECP_RESTARTABLE'
-
-        - os-image: ubuntu-latest
-          container: ubuntu:20.04
-          crypto-provider: Test
-
-    name: ${{ matrix.config.crypto-provider }} ${{ matrix.config.crypto-provider-version }} • ${{ matrix.c-compiler }} • ${{ matrix.config.container }}
+    name: ${{ matrix.crypto.interface}} • ${{ matrix.crypto.provider }} • ${{matrix.crypto.version}} • ${{ matrix.c-compiler }} • ${{ matrix.qcbor-version }} • ${{ matrix.ifdef }}
 
     runs-on: ${{ matrix.config.os-image }}
-    container: ${{ matrix.config.container }}
+ #   container: ${{ matrix.config.container }}
 
     steps:
     - uses: actions/checkout@v3
 
-    - name: Install build tools
-      run: |
-        set -ex
-        export DEBIAN_FRONTEND=noninteractive
-        apt-get update
-        apt-get install -y build-essential cmake python3 ${{ matrix.c-compiler }} \
-                python3-jinja2 python3-jsonschema
-        echo "CC=${{ matrix.c-compiler }}" >> $GITHUB_ENV
-    
-    - name: Install OpenSSL
-      if: matrix.config.crypto-provider == 'OpenSSL'
-      run: apt-get install -y libssl-dev
-
-    - name: Fetch MbedTLS
-      if: matrix.config.crypto-provider == 'MbedTLS'
-      uses: actions/checkout@v3
+    - name: Set up Python
+      uses: actions/setup-python@v5
       with:
-        repository: ARMmbed/mbedtls
-        ref: ${{ matrix.config.crypto-provider-version }}
-        path: mbedtls
+        python-version: "3.11"
 
-    - name: Install MbedTLS
-      if: matrix.config.crypto-provider == 'MbedTLS'
+    - name: Install Python dependencies
       run: |
-        cd mbedtls
-        ${{ matrix.config.crypto-provider-build-extra }}
-        make -j $(nproc)
-        make install
+        python -m pip install --upgrade pip
+
+    - name: Install Conan
+      run: pip install --upgrade conan
+
+    - name: Detect Conan profile
+      run: conan profile detect --force
+
+    - name: Install OpenSSL
+      if: matrix.crypto.provider == 'OpenSSL'
+      run: |
+        conan install \
+          --requires=openssl/${{ matrix.crypto.version }} \
+          --output-folder=build \
+          --build=missing \
+          -g CMakeDeps \
+          -g CMakeToolchain \
+          -s build_type=Debug
+
+    - name: Install mbedTLS with Conan (inline)
+      if: matrix.crypto.provider == 'MbedTLS'
+      shell: bash
+      run: |
+        conan install \
+          --requires=mbedtls/${{ matrix.crypto.version }} \
+          --output-folder=build \
+          --build=missing \
+          -g CMakeDeps \
+          -g CMakeToolchain \
+          -o mbedtls/*:enable_psa=True \
+          -s build_type=Debug
 
     - name: Fetch QCBOR
       uses: actions/checkout@v3
       with:
         repository: laurencelundblade/QCBOR
+        ref: ${{ matrix.qcbor-version }}
         path: QCBOR
 
-    - name: Install QCBOR
+    - name: Configure QCBOR
+      shell: bash
       run: |
         cd QCBOR
-        make -j$(nproc)
-        make install
+        cmake -S . -B qcbor-build 
+
+    - name: build QCBOR
+      shell: bash
+      run: |
+        cd QCBOR
+        cmake --build qcbor-build
+
+    - name: Install QCBOR
+      shell: bash
+      run: |
+        cd QCBOR
+        cmake --install qcbor-build --prefix "$GITHUB_WORKSPACE/install" 
+
+    - name: Configure t_cose
+      shell: bash
+      run: |
+        IFD="${{ matrix.ifdef }}"
+        if [ -z "$IFD" ]; then
+          CONDITIONAL=""
+        else
+          CONDITIONAL="-D${IFD}=ON"
+        fi
+        cmake -S . -B build \
+          -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON \
+          ${{ matrix.crypto.cmake }} \
+          -DCRYPTO_PROVIDER=${{ matrix.crypto.provider }} \
+          -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/install \
+          -DCMAKE_BUILD_TYPE=Debug \
+          "$CONDITIONAL"
 
     - name: Build t_cose
       run: |
         set -ex
-        mkdir build
-        cd build
-        cmake -DCRYPTO_PROVIDER=${{ matrix.config.crypto-provider }} \
-          ${{ matrix.config.crypto-provider-extra }} \
-          ${{ matrix.config.defines }} \
-          ..
-        make -j $(nproc)
+        cmake --build build --verbose
 
     - name: Run examples
       run: build/t_cose_examples
 
     - name: Run tests
-      if: matrix.config.crypto-provider == 'MbedTLS' &&
-          matrix.config.crypto-provider-version == 'v3.4.0' &&
-          matrix.config.crypto-provider-build-extra == ''
-      # This Mbed TLS version has the option of restartable ECP, however it is
-      # not turned on. In this case the restartable testcase should fail.
-      run: build/t_cose_test | grep 'restart_test_2_step FAILED'
+      run: build/t_cose_test
+
+  ifdef-fan-out:
+    strategy:
+      fail-fast: false
+      matrix:
+        c-compiler: [clang]
+
+        qcbor-version: [dev]
+
+        crypto:
+          - interface: Test
+            provider: Test
+            cmake: ""
+
+          - interface: psa
+            provider: MbedTLS
+            version: 2.28.9
+            cmake: -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake 
+
+          - interface: psa
+            provider: MbedTLS
+            version: 3.5.2
+            cmake: -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake 
+
+          - interface: OpenSSL
+            provider: OpenSSL
+            version: 1.1.1v
+            cmake: -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake 
+
+# TODO: re-enable this
+#          - interface: OpenSSL
+#            provider: OpenSSL
+#            version: 3.6.0
+#            cmake: -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake 
+
+        ifdef: &ifdef-array
+          - ""
+          - T_COSE_DISABLE_CONTENT_TYPE
+          - T_COSE_DISABLE_COSE_SIGN
+          - T_COSE_DISABLE_ES384
+          - T_COSE_DISABLE_ES512
+          - T_COSE_DISABLE_PS384
+          - T_COSE_DISABLE_PS256
+          - T_COSE_DISABLE_PS512
+          - T_COSE_DISABLE_ES384
+# TODO: re-enable this          - T_COSE_DISABLE_KEYWRAP
+          - T_COSE_DISABLE_SHORT_CIRCUIT_SIGN
+          - T_COSE_DISABLE_USAGE_GUARDS
+
+        config:
+          - os-image: ubuntu-latest
+            container: ubuntu:22.04
+
+    name: ${{ matrix.crypto.interface}} • ${{ matrix.crypto.provider }} • ${{matrix.crypto.version}} • ${{ matrix.c-compiler }} • ${{ matrix.qcbor-version }} • ${{ matrix.ifdef }}
+
+    runs-on: ${{ matrix.config.os-image }}
+ #   container: ${{ matrix.config.container }}
+
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: "3.11"
+
+    - name: Install Python dependencies
+      run: |
+        python -m pip install --upgrade pip
+
+    - name: Install Conan
+      run: pip install --upgrade conan
+
+    - name: Detect Conan profile
+      run: conan profile detect --force
+
+    - name: Install OpenSSL
+      if: matrix.crypto.provider == 'OpenSSL'
+      run: |
+        conan install \
+          --requires=openssl/${{ matrix.crypto.version }} \
+          --output-folder=build \
+          --build=missing \
+          -g CMakeDeps \
+          -g CMakeToolchain \
+          -s build_type=Debug
+
+    - name: Install mbedTLS with Conan (inline)
+      if: matrix.crypto.provider == 'MbedTLS'
+      shell: bash
+      run: |
+        conan install \
+          --requires=mbedtls/${{ matrix.crypto.version }} \
+          --output-folder=build \
+          --build=missing \
+          -g CMakeDeps \
+          -g CMakeToolchain \
+          -o mbedtls/*:enable_psa=True \
+          -s build_type=Debug
+
+    - name: Fetch QCBOR
+      uses: actions/checkout@v3
+      with:
+        repository: laurencelundblade/QCBOR
+        ref: ${{ matrix.qcbor-version }}
+        path: QCBOR
+
+    - name: Configure QCBOR
+      shell: bash
+      run: |
+        cd QCBOR
+        cmake -S . -B qcbor-build 
+
+    - name: build QCBOR
+      shell: bash
+      run: |
+        cd QCBOR
+        cmake --build qcbor-build
+
+    - name: Install QCBOR
+      shell: bash
+      run: |
+        cd QCBOR
+        cmake --install qcbor-build --prefix "$GITHUB_WORKSPACE/install" 
+
+    - name: Configure t_cose
+      shell: bash
+      run: |
+        IFD="${{ matrix.ifdef }}"
+        if [ -z "$IFD" ]; then
+          CONDITIONAL=""
+        else
+          CONDITIONAL="-D${IFD}=ON"
+        fi
+        cmake -S . -B build \
+          -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON \
+          ${{ matrix.crypto.cmake }} \
+          -DCRYPTO_PROVIDER=${{ matrix.crypto.provider }} \
+          -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/install \
+          -DCMAKE_BUILD_TYPE=Debug \
+          "$CONDITIONAL"
+
+    - name: Build t_cose
+      run: |
+        set -ex
+        cmake --build build --verbose
+
+    - name: Run examples
+      run: build/t_cose_examples
 
     - name: Run tests
-      if: ${{ ! ( matrix.config.crypto-provider == 'MbedTLS' &&
-              matrix.config.crypto-provider-version == 'v3.4.0' &&
-              matrix.config.crypto-provider-build-extra == '' ) }}
       run: build/t_cose_test
+
+  msvc:
+    name: msvc • windows-latest
+    runs-on: windows-latest
+
+    strategy:
+      fail-fast: false
+      matrix:
+        # TODO: add OPenSSL back in when we figure out why it is broken
+        crypto: [ Test, MbedTLS ]
+    
+    env:
+      ARCH: x64
+
+    steps:
+      - uses: actions/checkout@v4
+
+      # Optional: ensures Dev Cmd environment; the VS generator usually finds MSVC without this,
+      # but keeping it makes detection deterministic.
+      - name: Set up MSVC DevCmd
+        uses: ilammy/msvc-dev-cmd@v1
+        with:
+          arch: ${{ env.ARCH }}
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.11"
+
+      - name: Install Conan
+        run: pip install --upgrade conan
+
+      - name: Detect Conan profile
+        run: conan profile detect --force
+
+      - name: Install mbedTLS with Conan (inline)
+        shell: bash
+        run: |
+          conan install \
+            --requires=mbedtls/3.5.2 \
+            --output-folder=build \
+            --build=missing \
+            -g CMakeDeps \
+            -g CMakeToolchain \
+            -s compiler=msvc \
+            -s compiler.runtime=dynamic \
+            -o mbedtls/*:enable_psa=True \
+            -s build_type=Debug
+
+      - name: Fetch QCBOR Win
+        uses: actions/checkout@v3
+        with:
+          repository: laurencelundblade/QCBOR
+          ref: master
+          path: QCBOR
+
+      - name: Configure QCBOR Win
+        shell: bash
+        run: |
+          cd QCBOR
+          ARCH="${{ env.ARCH }}"
+          cmake -S . -B qcbor-build -G "Visual Studio 17 2022" -A "$ARCH" 
+
+      - name: build QCBOR Win
+        shell: bash
+        run: |
+          cd QCBOR
+          cmake --build qcbor-build 
+
+      - name: Install QCBOR Win
+        shell: bash
+        run: |
+          cd QCBOR
+          cmake --install qcbor-build --prefix "$GITHUB_WORKSPACE/install" --config Debug
+
+      - name: Install OpenSSL with vcpkg
+        uses: lukka/run-vcpkg@v11
+        with:
+          vcpkgJsonGlob: '**/vcpkg.json'
+
+      - name: Config t_cose
+        shell: bash
+        run: |
+          cmake -S . -B build \
+          -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/install" \
+          -DBUILD_TESTS=ON  -DBUILD_EXAMPLES=ON \
+          -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
+          -DCRYPTO_PROVIDER=${{ matrix.crypto }} 
+
+      - name: Build t_cose
+        run: cmake --build build --config Debug
+        shell: bash
+
+      - name: Run tests
+        shell: pwsh
+        run: |
+          $exe = "build/Debug/t_cose_test.exe"
+          if (!(Test-Path $exe)) {
+            Write-Error "Test binary not found: $exe"
+          }
+          & $exe 
